[package]
name = "bevy_fluent"
version = "0.1.1"
authors = ["g <kgv@users.noreply.github.com>"]
edition = "2018"
description = "Bevy plugin for localization using Fluent"
readme = "README.md"
homepage = "https://crates.io/crates/bevy_fluent"
repository = "https://github.com/kgv/bevy_fluent"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "gamedev", "internationalization", "localization", "plugin"]
categories = ["games", "game-development", "internationalization", "localization"]
exclude = [".github/**/*", "assets/**/*"]

[dependencies]
anyhow = "1.0.38"
bevy = { git = "https://github.com/bevyengine/bevy", rev = "284889c64b2a4a4f67018e42a14062392edbd0aa", default-features = false }
fluent = "0.15.0"
fluent-langneg = "0.13.0"
indexmap = "1.6.1"
intl-memoizer = "0.5.1"
ron = "0.6.4"
serde = { version = "1.0.123", features = ["derive"] }
typed-builder = "0.9.0"
unic-langid = { version = "0.9.0", features = ["macros", "serde"] }
walkdir = "2.3.1"

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "284889c64b2a4a4f67018e42a14062392edbd0aa", default-features = false, features = ["bevy_winit", "x11"] }

[features]
default = []
# default = ["implicit"]
implicit = []