[package]
name = "bevy_fluent"
version = "0.0.1"
authors = ["g <kgv@users.noreply.github.com>"]
edition = "2018"
description = "A Bevy plugin for localization using Fluent."
readme = "README.md"
homepage = "https://crates.io/crates/bevy_fluent"
repository = "https://github.com/kgv/bevy_fluent"
license = "MIT OR Apache-2.0"
keywords = ["gamedev", "internationalization", "language", "localization", "plugin"]
categories = ["games", "game-development", "internationalization", "localization"]

[dependencies]
anyhow = "1.0.38"
bevy = "0.4.0"
fluent = "0.15.0"
fluent-syntax = "0.11.0"
intl-memoizer = "0.5.1"
log = "0.4.14"
ron = "0.6.4"
serde = { version = "1.0.123", features = ["derive"] }
thiserror = "1.0.23"
typed-builder = "0.9.0"
unic-langid = { version = "0.9.0", features = ["macros", "serde"] }